export const initialState = {
    cards: [
        {id: 1, done: false, isOpen: false, title: '🔥'},
        {id: 2, done: false, isOpen: false, title: '😜'},
        {id: 3, done: false, isOpen: false, title: '🤬'},
        {id: 4, done: false, isOpen: false, title: '🤡'},
        {id: 5, done: false, isOpen: false, title: '💩'},
        {id: 6, done: false, isOpen: false, title: '🤡'},
        {id: 7, done: false, isOpen: false, title: '🔥'},
        {id: 8, done: false, isOpen: false, title: '🐸'},
        {id: 9, done: false, isOpen: false, title: '💩'},
        {id: 10, done: false, isOpen: false, title: '✊'},
        {id: 11, done: false, isOpen: false, title: '😜'},
        {id: 12, done: false, isOpen: false, title: '👨‍👩‍👧'},
        {id: 13, done: false, isOpen: false, title: '🐸'},
        {id: 14, done: false, isOpen: false, title: '🤬'},
        {id: 15, done: false, isOpen: false, title: '👨‍👩‍👧'},
        {id: 16, done: false, isOpen: false, title: '🚚'},
        {id: 17, done: false, isOpen: false, title: '👻'},
        {id: 18, done: false, isOpen: false, title: '🚚'},
        {id: 19, done: false, isOpen: false, title: '👻'},
        {id: 20, done: false, isOpen: false, title: '✊'},
    ],
    newCards: [
        {id: 21, done: false, isOpen: false, title: '📌'},
        {id: 22, done: false, isOpen: false, title: '❤️'},
        {id: 23, done: false, isOpen: false, title: '🍉'},
        {id: 24, done: false, isOpen: false, title: '🤣'},
        {id: 25, done: false, isOpen: false, title: '👁'},
        {id: 26, done: false, isOpen: false, title: '❄️'},
        {id: 27, done: false, isOpen: false, title: '📌'},
        {id: 28, done: false, isOpen: false, title: '🍉'},
        {id: 29, done: false, isOpen: false, title: '🤣'},
        {id: 30, done: false, isOpen: false, title: '❤️'},
        {id: 31, done: false, isOpen: false, title: '❄️'},
        {id: 32, done: false, isOpen: false, title: '👁'},
        {id: 33, done: false, isOpen: false, title: '🏎'},
        {id: 34, done: false, isOpen: false, title: '⭐️'},
        {id: 35, done: false, isOpen: false, title: '🤘🏻'},
        {id: 36, done: false, isOpen: false, title: '💀'},
        {id: 37, done: false, isOpen: false, title: '🤘🏻'},
        {id: 38, done: false, isOpen: false, title: '💀'},
        {id: 39, done: false, isOpen: false, title: '🏎'},
        {id: 40, done: false, isOpen: false, title: '⭐️'},
    ],
    counter: 0,
    isLose: false,
    isWin: false,
    level: 1,
}
